/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import spock.lang.Specification

class AppTest extends Specification {
    def "pipeline executes without throwing for valid config"() {
        setup:
        def config = [
            appName: "my-app",
            version: "1.0.0",
            env    : "test"
        ]
        def pipeline = new Pipeline(config)

        when:
        pipeline.execute()

        then:
        noExceptionThrown()
    }
}
